--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FlxiBoy1313/Perks
build-by-default: true
branches:
- main
projects:
  Perks:
    path: ""
    php: 8.0
    icon: "icon.png"
    libs:
      - src: https://poggit.pmmp.io/ci/Vecnavium/FormsUI/FormsUI
        version: ^1.1.1
...
