######################
######################
####                               ####
####     Perks System     ####
####                               ####
######################
######################

# language list: english, german, russian
# more languages? please open a issues on github for a new language.
language: english

# command, edit the perks command
command:
  cmd: "perk"
  desc: "Open the Perk UI"
  usage: "§cUsage: /perk"
  aliases: "perks"
  reload:
    usage: "§cUsage: /perk <reload>"
    perms: perk.reload
  # if false, then this does not apply. if you write something, then the command goes.
  permission: false
  # If this is true, you can only buy with the price. If this is false, it goes to Permissions.
  economy-api: false
   # if this is true and 'economy-api' is also true, then you can give friends perks.
  friends:
    enable: false
    menu-img: "textures/ui/Friend2"
    yes-img: "textures/ui/confirm"
    no-img: "textures/ui/redX1"

perk:
    # perms => if you set it to false, anyone can use it. With a permission, this is only possible if a player has did permission.
    # price => will only go if you have 'economy-api' to true. This sets the price of the perk.
    # img => there you can add your picture or a picture of minecraft. false is disable the img. Is your picture not loading? Then install FormImagesFix.
    # order => so you can decide the order of the perks. If you don't have the perk inside, it won't show up either. list: "speed", "jump", "haste", "night-vision", "no-hunger", "no-falldamage", "fast-regeneration", "keep-inventory", "dopple-xp", "strength", "no-firedamage", "fly", "water-breathing", "invisibility"
  perms:
    # if this true, then only the perks are shown, as you also have hats or the permission, the perks should go with permission.
    enable: false
  order:
    - "speed"
    - "jump"
    - "haste"
    - "night-vision"
    - "no-hunger"
    - "no-falldamage"
    - "fast-regeneration"
    - "keep-inventory"
    - "dopple-xp"
    - "strength"
    - "no-firedamage"
    - "fly"
    - "water-breathing"
    - "invisibility"
  speed:
    perms: perk.speed
    price: 10000
    img: "textures/ui/speed_effect"
  jump:
    perms: perk.jump
    price: 10000
    img: "textures/ui/jump_boost_effect"
  haste:
    perms: perk.haste
    price: 10000
    img: "textures/ui/haste_effect"
  night-vision:
    perms: perk.night-vision
    price: 10000
    img: "textures/items/potion_bottle_nightVision"
  no-hunger:
    perms: perk.no-hunger
    price: 10000
    img: "textures/ui/hunger_full"
  no-falldamage:
    perms: perk.no-falldamage
    price: 10000
    img: "textures/items/totem"
  fast-regeneration:
    perms: perk.fast-regeneration
    price: 10000
    img: "textures/ui/regeneration_effect"
  keep-inventory:
    perms: perk.keep-inventory
    price: 10000
    img: "textures/blocks/chest_front"
  dopple-xp:
    perms: perk.dopple-xp
    price: 10000
    img: "textures/ui/dust_selectable_2"
  strength:
    perms: perk.stren
    price: 10000
    img: "textures/ui/strength_effect"
  no-firedamage:
    perms: perk.no-firedamage
    price: 10000
    img: "textures/ui/fire_resistance_effect"
  fly:
    perms: perk.fly
    price: 10000
    img: "textures/items/feather"
  water-breathing:
    perms: perk.water-breathing
    price: 10000
    img: "textures/ui/water_breathing_effect"
  invisibility:
    perms: perk.invisibility
    price: 10000
    img: "textures/ui/invisibility_effect"