####################################
####################################
#######                      #######
#######     Perks System     #######
#######                      #######
####################################
####################################

# language list: english, german, russian
# more languages? please open a issues on GitHub for a new language.
language: english

# command, edit the perks command
command:
  cmd: "perk"
  desc: "Open the Perks UI"
  usage: "§cUsage: /perks"
  aliases: ["perks"]
  # If this is set to false, anyone can use this command. If this is true, then this is only possible with the permission Perks.command
  permission: false

settings:
  economy:
    # If this is true, you can only buy with the price.
    enable: false
    # types: EconomyAPI, BedrockEconomy
    typ: "EconomyAPI"
  friends:
    # if this and 'economy-api' true, then you can give friends perks.
    enable: true
    menu-img: "textures/ui/Friend2"
    yes-img: "textures/ui/confirm"
    no-img: "textures/ui/redX1"
    # if this true, then a UI will be opened to the person who has bought a perk
    open-ui: true
  perk-time:
    # if this and 'economy-api' true, then perks will only be there for a certain time.
    enable: false
    # %year% => is the year
    # %month% => is the month
    # %day% => is the day
    # %hour% => is the hour
    # %minute% => is the minute
    format: "§e%year% §ayear, §e%month% §amonth, §e%day% §aday, §e%hour% §ahour, §e%minute% §aminute"
    # enter the number of seconds to set the duration of the Perks Times Check, 1 = 1 second, 60 = 1 minute
    time-task: 60
  buy-confirm:
    # if this true, then a query is made before buying
    enable: false
    yes-img: "textures/ui/confirm"
    no-img: "textures/ui/redX1"
  double-jump:
    # This sets the strength of the double jump.
    strength: 1.4
  auto-smelting:
    # if this is true then the items will be melted.
    enable: true
    # this is what makes the price of smelting
    price: 150
  perks-strength:
    # this is the max strength of perk strength
    strength: 5
  per-world:
  #  if this true, then you can only use perks in certain worlds
    enable: false
    # list of the worlds
    worlds:
    - world
    - world2

# category
#   tutorial
#      category:
#        <number +>:
#           name: "<category-name>:<picture false is disable>"
#           perks: 
#             - "<perk-names>"
#  perk-list: "speed", "jump", "haste", "night-vision", "no-hunger", "no-falldamage", "fast-regeneration", "keep-inventory", "double-xp", "strength", "no-firedamage", "fly", "water-breathing", "invisibility", "keep-xp", "double-jump", "auto-smelting"
category:
  0:
    name: "§5Effects:textures/ui/absorption_effect"
    perks:
      - "speed"
      - "jump"
      - "haste"
      - "night-vision"
      - "fast-regeneration"
      - "strength"
      - "no-firedamage"
      - "water-breathing"
      - "invisibility"
  1:
    name: "§2Others:textures/ui/more-dots"
    perks:
      - "no-hunger"
      - "no-falldamage"
      - "keep-inventory"
      - "double-xp"
      - "fly"
      - "keep-xp"
      - "double-jump"
      - "auto-smelting"

# perks
perk:
  # perms => if this false, then it works without permission, if this not false, then it goes with Permission
  # price => will only go if you have 'economy-api' to true. This sets the price of the perks.
  # img => there you can add your picture or a picture of minecraft. false is disable the img. Is your picture not loading? Then install FormImagesFix.
  # time => if 'economy-api' true, this tells how long you can use a perk after buying it and then buy it again.
  #               0:0:0:0:0 => Year:Month:Day:Hour:Minute => 0:0:6:24:59 (time zone => your server location)
  perms:
    # If this is true, only perks that you have bought will be shown
    enable: false
  speed:
    perms: false
    price: 10000
    img: "textures/ui/speed_effect"
    time: "0:0:7:0:0"
  jump:
    perms: false
    price: 10000
    img: "textures/ui/jump_boost_effect"
    time: "0:0:7:0:0"
  haste:
    perms: false
    price: 10000
    img: "textures/ui/haste_effect"
    time: "0:0:7:0:0"
  night-vision:
    perms: false
    price: 10000
    img: "textures/items/potion_bottle_nightVision"
    time: "0:0:7:0:0"
  no-hunger:
    perms: false
    price: 10000
    img: "textures/ui/hunger_full"
    time: "0:0:7:0:0"
  no-falldamage:
    perms: false
    price: 10000
    img: "textures/items/totem"
    time: "0:0:7:0:0"
  fast-regeneration:
    perms: false
    price: 10000
    img: "textures/ui/regeneration_effect"
    time: "0:0:7:0:0"
  keep-inventory:
    perms: false
    price: 10000
    img: "textures/ui/inventory_icon"
    time: "0:0:7:0:0"
  double-xp:
    perms: false
    price: 10000
    img: "textures/ui/dust_selectable_2"
    time: "0:0:7:0:0"
  strength:
    perms: false
    price: 10000
    img: "textures/ui/strength_effect"
    time: "0:0:7:0:0"
  no-firedamage:
    perms: false
    price: 10000
    img: "textures/ui/fire_resistance_effect"
    time: "0:0:7:0:0"
  fly:
    perms: false
    price: 10000
    img: "textures/items/feather"
    time: "0:0:7:0:0"
  water-breathing:
    perms: false
    price: 10000
    img: "textures/ui/water_breathing_effect"
    time: "0:0:7:0:0"
  invisibility:
    perms: false
    price: 10000
    img: "textures/ui/invisibility_effect"
    time: "0:0:7:0:0"
  keep-xp:
    perms: false
    price: 10000
    img: "textures/ui/dust_selectable_1"
    time: "0:0:7:0:0"
  double-jump:
    perms: false
    price: 10000
    img: "textures/items/iron_boots"
    time: "0:0:7:0:0"
  auto-smelting:
    perms: false
    price: 10000
    img: "textures/blocks/furnace_front_on"
    time: "0:0:7:0:0"